### ISSUE TITLE
CRAVE price

### ISSUE THREAD

**Issue by TheRealSlothman** [CRAVEMasterNodesDev/CRAVEMasterNodesPro#2]
It does not look like the crave > btc price is being changed or updated.

The same price has been showing for the last 12-18 hours.

**Comment by TheRealSlothman** [comment]
Looks like it just changed.  Thanks.  Believe this should mean it is correctly pulling in the data.

**Comment by TheRealSlothman** [comment]
Closed too soon.  Believe this is being resolved though.

**Comment by JSponaugle** [comment]
This has been resolved now!!!!
