### ISSUE TITLE
CRAVE per day

### ISSUE THREAD

**Issue by TheRealSlothman** [CRAVEMasterNodesDev/CRAVEMasterNodesPro#3]
The crave received per day is becoming more and more inaccurate.  It just keeps increasing, meaning the ROI is now more than 4x too high.

Must be an incorrect calculation somewhere, as there is no way this is correct.

**Comment by JSponaugle** [comment]
I am tracking crave blockchain and going to find out the solution to this.

**Comment by JSponaugle** [comment]
This has been resolved now !!!!
